### ISSUE TITLE
Accessing the API - How to aunthanicate

### ISSUE THREAD

**Issue by gauravo7** [prionkor/yith-woocommerce-wishlist-rest-api#2]
After Searching i come to Your Nice work. 
I need little help in using your plugin . i know the checklist you mark documentation is pending but i need help
I tried to access the /wp-json/yith/wishlist/v1/wishlists/ but it says **Authentication Required**
i try to pass rest api secret and key also. Can you please tell me how to authenticate the apis.

**Comment by prionkor** [comment]
Hello, Sorry for the late response. Generally you should be able to authenticate with any auth method. The plugin doesn't enforce any login type. It just uses `is_user_logged_in()` function. 

For rest API key and secrets I think there is no user is set by Wordpress. That is why you are having the issue. You will need a user based authentication. 

Check out https://wordpress.org/plugins/jwt-auth/

**Comment by gauravo7** [comment]
Thanks @prionkor  for reply and let me check this
